function [U, V] = step_compact(u, v, up, vp, params)
% D = params.D;
h = params.h;
tau = params.tau;

a = params.a;
b = 1;
c = (tau + 2*a*tau)/(2*h^2);
e = -(tau + 2*a*tau)/h^2;
p = a*tau/2;
q = tau/2;

C = params.C;
E = 1; % E coefficient (of the compact scheme)
A = -(tau + 2*C*tau)/(2*h^2);
B = (tau + 2*C*tau)/h^2;
P = C*tau/2;
Q = tau/2;

upj2 = circshift(up, -1);
upj0 = circshift(up, 1);
vpj2 = circshift(vp, -1);
vpj0 = circshift(vp, 1);
uj2 = circshift(u, -1);
uj0 = circshift(u, 1);
vj2 = circshift(v, -1);
vj0 = circshift(v, 1);

F = -a*upj0 - b*up - a*upj2 ...
    +a*uj0 + b*u + a*uj2 ...
    -c*vpj0 - e*vp - c*vpj2 ...
    -c*vj0 - e*v - c*vj2 + ...
    +p*(upj0.^2 + vpj0.^2).*vpj0 ...
    +q*(up.^2 + vp.^2).*vp ...
    +p*(upj2.^2 + vpj2.^2).*vpj2 ...
    +p*(uj0.^2 + vj0.^2).*vj0 ...
    +q*(u.^2 + v.^2).*v ...
    +p*(uj2.^2 + vj2.^2).*vj2;

Feps = diag(b - 2*q*up.*vp) + ...
    diag(a - 2*p*up(2:end).*vp(2:end), 1) + ...
    diag(a - 2*p*up(1:end-1).*vp(1:end-1), -1);
Feps(1, end) = a - 2*p*up(end).*vp(end);
Feps(end, 1) = a - 2*p*up(1).*vp(1);

Fdelta = diag(e - q*(up.^2 + 3*vp.^2)) + ...
    diag(c - p*(up(2:end).^2 + 3*vp(2:end).^2), 1) + ...
    diag(c - p*(up(1:end-1).^2 + 3*vp(1:end-1).^2), -1);
Fdelta(1, end) = c - p*(up(end).^2 + 3*vp(end).^2);
Fdelta(end, 1) = c - p*(up(1).^2 + 3*vp(1).^2);

G = -A*upj0 - B*up - A*upj2 ...
    -A*uj0 - B*u - A*uj2 ...
    -C*vpj0 - E*vp - C*vpj2 ...
    +C*vj0 + E*v + C*vj2 + ...
    +P*(upj0.^2 + vpj0.^2).*upj0 ...
    +Q*(up.^2 + vp.^2).*up ...
    +P*(upj2.^2 + vpj2.^2).*upj2 ...
    +P*(uj0.^2 + vj0.^2).*uj0 ...
    +Q*(u.^2 + v.^2).*u ...
    +P*(uj2.^2 + vj2.^2).*uj2;

% G = -A*upj0 - B*up - A*upj2 ...
%     -A*uj0 - B*u - A*uj2 ...
%     -C*vpj0 - E*vp - C*vpj2 ...
%     +C*vj0 + E*v + C*vj2 + ...
%     +P*(upj0.^2 + vpj0.^2).*upj0 ...
%     +Q*(up.^2 + vp.^2).*up ...
%     +P*(upj2.^2 + vpj2.^2).*upj2 ...
%     +P*(uj0.^2 + vj0.^2).*uj0 ...
%     +Q*(u.^2 + v.^2).*u ...
%     +P*(uj2.^2 + vj2.^2).*uj2;

Geps = diag(B - Q*(3*up.^2 + vp.^2)) + ...
    diag(A - P*(3*up(2:end).^2 + vp(2:end).^2), 1) + ...
    diag(A - P*(3*up(1:end-1).^2 + vp(1:end-1).^2), -1);
Geps(1, end) = A - P*(3*up(end).^2 + vp(end).^2);
Geps(end, 1) = A - P*(3*up(1).^2 + vp(1).^2);

Gdelta = diag(E - 2*Q*up.*vp) + ...
    diag(C - 2*P*up(2:end).*vp(2:end), 1) + ...
    diag(C - 2*P*up(1:end-1).*vp(1:end-1), -1);
Gdelta(1, end) = C - 2*P*up(end).*vp(end);
Gdelta(end, 1) = C - 2*P*up(1).*vp(1);

M = [Feps, Fdelta;
    Geps, Gdelta];
ED = M \ [F, G].';

N = length(ED);
Eps = ED(1 : N/2);
Delta = ED(N/2 + 1 : end);
uc = u + Eps.';
vc = v + Delta.';

U = uc;
V = vc;
end
